name: Gotenberg continuous integration
on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: make lint
      - run: make tests