name: tests_maybe_release

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  tests_maybe_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v1
      - name: Lint code
        run: make lint
      - name: Run tests
        run: |
          make tests CODE_COVERAGE=1
          bash <(curl -s https://codecov.io/bash)
      - name: Release
        if: ${{ github.event_name == 'release' }}
        run: make publish VERSION=${{ github.event.release.tag_name }} DOCKER_USER=${{ secrets.DOCKER_USER }} DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}